spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/insurance_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.insuranceservice.backend: DEBUG

